### PR TITLE
Allow GET access to node_modules/place-my-order-assets.

### PR DESCRIPTION
**Pull request by rlmcneary2**
Use feathers.static to allow access to the owning project's node_modules directory.

### CODE REVIEW

**Review by justinbmeyer — COMMENTED** [review]
Will this get the right node_modules folder no matter where this project is?

**Comment by BigAB** [comment]
This isn't really what we wanted anyway is it? Does it solve the problem?

I wanted to set up a route in the API `/api/images/` that would return images, and then change the data the api returns to have the images point to that image server/api

**Comment by rlmcneary2** [comment]
@BigAB  you are right. This change is fine for the donejs pmo, but because angular pmo changes the URL it will be broken? That's too bad because this is a simple fix that solves the problem without changing the data that that the api returns - I feel like its a good solution because the api provides a URL that it can serve. Although I think adding another static for the path the angular app expects would fix that problem. Have to investigate more.

**Comment by rlmcneary2** [comment]
In the response for cities a new property named "resources" has been added with image properties that have URLs starting with `api/resources`.

The `api/resources` URLs map to the `node_modules/place-my-order-assets` directory. For example the URL `http://localhost:3000/api/resources/images/4-thumbnail.jpg` will be routed to `node_modules/place-my-order-assets/images/4-thumbnail.jpg`.

This requires that any project that uses place-my-order-api **must also** have place-my-order-assets installed; this seems OK to me.

**Comment by BigAB** [comment]
Is `place-my-order-assets` a dependancy of `place-my-order-api`?
Perhaps it should be.

**Comment by rlmcneary2** [comment]
That was the original thought but I don't feel like its necessary. If you want to use the api/resources path then install pmoa. But I don't feel strongly about it.

**Comment by rlmcneary2** [comment]
For the react app it will be installed anyway to use it for `import`.

**Comment by justinbmeyer** [comment]
it should be a dependency probably. Self contained app is a good thing.

**Comment by justinbmeyer** [comment]
Especially as we might host just the server

**Comment by rlmcneary2** [comment]
The place-my-order-assets package is bundled so it always appears under this package in `node_modules`. At startup the path to resources is output.

**Comment by rlmcneary2** [comment]
Can I go ahead and merge this then publish a "next" package to test it deploying from npmjs?

**Comment by justinbmeyer** [comment]
Yeah!

**Comment by rlmcneary2** [comment]
Created a 1.1.0 branch with these changes and will merge that into master after beta test.

**Pull request closed without merging**
